package com.juicemilk.community.model;

public class QuestionCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_COLLECT.ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_COLLECT.USER_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_COLLECT.QUESTION_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_COLLECT.GMT_CREATE
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_COLLECT.ID
     *
     * @return the value of QUESTION_COLLECT.ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_COLLECT.ID
     *
     * @param id the value for QUESTION_COLLECT.ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_COLLECT.USER_ID
     *
     * @return the value of QUESTION_COLLECT.USER_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_COLLECT.USER_ID
     *
     * @param userId the value for QUESTION_COLLECT.USER_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_COLLECT.QUESTION_ID
     *
     * @return the value of QUESTION_COLLECT.QUESTION_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_COLLECT.QUESTION_ID
     *
     * @param questionId the value for QUESTION_COLLECT.QUESTION_ID
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_COLLECT.GMT_CREATE
     *
     * @return the value of QUESTION_COLLECT.GMT_CREATE
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_COLLECT.GMT_CREATE
     *
     * @param gmtCreate the value for QUESTION_COLLECT.GMT_CREATE
     *
     * @mbg.generated Thu Feb 20 22:22:45 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}